# Site settings
name: Less Or More
email: ccl_cm@163.com
author: Chen Chao Li
url: http://www.hifreud.com
resume_site: https://cclcm.github.io/chenchaoli.github.io/
github: https://github.com/CCLCM
#baseurl: "/LessOrMore"
description: Actually, less is more!
meta_description: 康志华;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: 陈超利

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

