# Site settings
name: Chao Li Chen
email: ccl_cm@163.com
author: ChaoLi Chen
url: https://cclcm.github.io/chenchaoli.github.io/
resume_site: https://cclcm.github.io/chenchaoli.github.io/
github: https://github.com/CCLCM
baseurl: ""
description: 实际上, 少就是多!
meta_description: 生命不止;折腾不休
motto: 坚持不懈,任重而道远
banner: 坚持不懈,任重而道远。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: CCLCM

# Build settings
markdown: kramdown
